# Cloudflare Pages 配置
name = "chuanzhibei"
compatibility_date = "2026-04-06"

# Pages 构建配置
pages_build_output_dir = "grennn_web/dist"

# Pages 静态资源配置
[assets]
not_found_handling = "single-page-application"
