/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthAnimation: typeof import('./src/components/auth/AuthAnimation.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/ui/BaseInput.vue')['default']
    DataDashboard: typeof import('./src/components/data/DataDashboard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    NavIcons: typeof import('./src/components/icons/NavIcons.vue')['default']
    ResilienceProgress: typeof import('./src/components/data/ResilienceProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollIndicator: typeof import('./src/components/feedback/ScrollIndicator.vue')['default']
    Silk: typeof import('./src/components/effects/Silk.vue')['default']
    SkeletonLoader: typeof import('./src/components/ui/SkeletonLoader.vue')['default']
    SoilFundBackground: typeof import('./src/components/backgrounds/SoilFundBackground.vue')['default']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheIntro: typeof import('./src/components/layout/TheIntro.vue')['default']
    TheNavbar: typeof import('./src/components/layout/TheNavbar.vue')['default']
    TheSidebar: typeof import('./src/components/layout/TheSidebar.vue')['default']
    WeatherIcon: typeof import('./src/components/weather/WeatherIcon.vue')['default']
  }
}
